 language: python

 git:
   depth: 1

 install:
   - pip install codecov

 python: "3.6"

 # script to run tests. Script can have many commands, one per line.
 script:
   - coverage run -m unittest discover -p "*_test.py"

 after_success:
   - codecov